### ISSUE TITLE
Crash when you delete screenshot

### ISSUE THREAD

**Issue by barraIhsan** [LotuxPunk/Nicephore-Fabric#1]
So first you open the screenshot GUI first, then you delete the screenshot (for example here the 3rd screenshot) from the file explorer. Then you navigate to the 3rd image (GUI), then it will crash
Crash report : https://gist.githubusercontent.com/natanfudge/4ed07f1945da9724f1ce5d9cbf2a0c47/raw/f7fff04bec3ff82a6a1f56534d8fe2396d3f32fd/crash.txt

Note : Also why there is a folder called `nicephore` in `.minecraft/mods`? and there is like readme, and the exe?

**Comment by LotuxPunk** [comment]
Hey, thanks for the report ! I'll look at it right now.

> Note : Also why there is a folder called `nicephore` in `.minecraft/mods?` and there is like readme, and the exe?

That's the folder used to store executable that allow the mod to optimise image/screenshots you make, if you don't want thos, you can just disable that feature on the config file delete that folder and you should never get it again. :)

**Comment by barraIhsan** [comment]
Oh also i just realised that sometimes the .jpg is completely black

**Comment by LotuxPunk** [comment]
Could you try to repoduce that and send the image + latest.log when that happens please ? :)
