### ISSUE TITLE
Freezes on screenshot

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [LotuxPunk/Nicephore-Fabric#11]
Model Name: Mac mini
Model Identifier: Macmini9,1
Chip: Apple M1
Total Number of Cores: 8 (4 performance and 4 efficiency)
Memory: 16 GB

When I press f2 to take a screenshot it freezes. Nothing in the output log. I have to force-quit from activity monitor.
Version: [nicephore-fabric-1.18.x-1.2.1.jar](https://www.curseforge.com/minecraft/mc-mods/nicephore-fabric/files/3651224) 
Game Version: 1.18.1 Fabric

**Comment by LotuxPunk** [comment]
Hello ! Have you change anything in the configuration file ?
I just tested with a MacBook Pro M1 and it's working smoothly on my side.
Depending if you enabled it or not, have you opt-in the permission check for the clipboarding feature ?

**Comment by RealHypnoticOcelot** [comment]
[nicephore.json.zip](https://github.com/LotuxPunk/Nicephore-Fabric/files/8182459/nicephore.json.zip)

**Comment by RealHypnoticOcelot** [comment]
Screenshot to clipboard is enabled.
