### ISSUE TITLE
Feature request: Config in ModMenu

### ISSUE THREAD

**Issue by HoodieRocks** [LotuxPunk/Nicephore-Fabric#12]
I would like to suggest adding a way to configure the mod from ModMenu. I don't believe this is already a feature

**Comment by LotuxPunk** [comment]
I'm planning to add my own implementation of a setting GUI 😁

Coming soon ™️

**Comment by Eatham532** [comment]
It still would be good to have the config menu link with ModMenu

**Comment by HoodieRocks** [comment]
Project doesn't look active anymore
