### ISSUE TITLE
Backslash instead of shash

### ISSUE THREAD

**Issue by cjvth** [LotuxPunk/Nicephore-Fabric#2]
I am using Linux. After using this mod I found in .minecraft mods\nicephore folder and \references.json file in it. 
![изображение](https://user-images.githubusercontent.com/40120650/114683034-dc522600-9d39-11eb-9f21-a619c4d96250.png)
![изображение](https://user-images.githubusercontent.com/40120650/114683067-e7a55180-9d39-11eb-9369-cf5163cc88a0.png)
Seems like it was expected to be in mods folder and the bug didn't show up on Windows

**Comment by LotuxPunk** [comment]
Hello ! Thanks for the report ! It should be fixed in the next build. 📦
