### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by Xrey274** [LotuxPunk/Nicephore-Fabric#20]
Could the mod be updated 1.19.3?

**Comment by LotuxPunk** [comment]
Should be compatible actually, did you tried the 1.19.2 version ?

**Comment by Xrey274** [comment]
Nope, opening the gallery or screenshot menu crashes the client.
[crash-2023-02-06_15.54.37-client.txt](https://github.com/LotuxPunk/Nicephore-Fabric/files/10663742/crash-2023-02-06_15.54.37-client.txt)
[crash-2023-02-06_15.55.28-client.txt](https://github.com/LotuxPunk/Nicephore-Fabric/files/10663743/crash-2023-02-06_15.55.28-client.txt)

**Comment by LotuxPunk** [comment]
Thanks, I'll take a look as soon as possible
