### ISSUE TITLE
Update 1.20 ?

### ISSUE THREAD

**Issue by ORN-Fox** [LotuxPunk/Nicephore-Fabric#23]
Hi, I love this mod so much (Great work 👏) that I was wondering if going to be updated for 1.20 ?

**Comment by LotuxPunk** [comment]
Hi ! Thanks !

That's planned, I'll try to come with something soon

**Comment by ORN-Fox** [comment]
Hi ! Still no version 1.20 coming?

**Comment by ORN-Fox** [comment]
Hi :) Anything new for version 1.20? 1.21 won't be long either :sweat_smile:
