### ISSUE TITLE
Crashes when opening screenshots menu in 1.17

### ISSUE THREAD

**Issue by dbrighthd** [LotuxPunk/Nicephore-Fabric#4]
I can copy screenshots, but when I press "g" my game crashes

**Comment by LotuxPunk** [comment]
Hello ! Thanks d'or the feedback ! The mod isn't ready yet for the 1.17, stay tuned for the update !

**Comment by srnyx** [comment]
@LotuxPunk have you abandoned this?

**Comment by LotuxPunk** [comment]
1.17 isn't supported yet, I'm working on it

**Comment by LotuxPunk** [comment]
> 1.17 isn't supported yet, I'm working on it

**Comment by LotuxPunk** [comment]
@srnyx You can see that some work is made on the Forge repo

**Comment by srnyx** [comment]
> @srnyx You can see that some work is made on the Forge repo

Ah, ok
