### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by Madis0** [LotuxPunk/Nicephore-Fabric#5]
The screenshot browser could have a delete button as well, preferably with a confirmation.

**Comment by LotuxPunk** [comment]
Isn't it already the case ?

**Comment by Madis0** [comment]
Actually, I don't know. I was going after the gif on Curseforge 😄

**Comment by LotuxPunk** [comment]
> Actually, I don't know. I was going after the gif on Curseforge 😄

Ahah, fine, that's an outdated gif.

I think even Fabric have this feature, with a confirmation screen !
