### ISSUE TITLE
Crash when trying to delete a non-existent screenshot

### ISSUE THREAD

**Issue by Felix14-v2** [LotuxPunk/Nicephore-Fabric#6]
**To reproduce**
1) Take a screenshot
2) Open the screenshots menu
3) Delete this screenshot using file explorer
4) Try to delete this screenshot via menu
5) Get crash

[crash-2021-09-12_19.34.48-client.txt](https://github.com/LotuxPunk/Nicephore-Fabric/files/7149991/crash-2021-09-12_19.34.48-client.txt)

**Comment by LotuxPunk** [comment]
Hey ! That's indeed a crash, even if I don't know why someone would do it that way... 😅 

Thanks for the report, I'll handle it !
