### ISSUE TITLE
Attempting to copy the last taken screenshot to the clipboard crashes the game.

### ISSUE THREAD

**Issue by Corvus20** [LotuxPunk/Nicephore-Fabric#8]
[crash-2021-12-14_22.13.08-client.txt](https://github.com/LotuxPunk/Nicephore-Fabric/files/7716241/crash-2021-12-14_22.13.08-client.txt)

Idk what is going on here, but its obviously isn't intended.

**Comment by LotuxPunk** [comment]
Hey ! Thanks for the report !
This is actually fixed in the code a release should be there soon.

At least the game isn't gonna crash if the clipboard failed to copy.

What can cause this issue is another mod that change the stuff that I need for copy the image to the clipboard

**Comment by LotuxPunk** [comment]
Should be fixed in the latest updates !
