### ISSUE TITLE
Upload to Modrinth

### ISSUE THREAD

**Issue by xXKasmaXx** [LotuxPunk/Nicephore-Fabric#9]
Hello please upload your mod to [Modrinth](modrinth.com). Or i could upload and update it there with your permission

**Comment by LotuxPunk** [comment]
Hello ! I do not wish to distribute Nicephore otherwise than on CurseForge. Once Modrinth will clarify its roadmap about mod author rewards, I'll probably do it myself.

Thanks anyway for your feedback!
